In [ ]:
import pandas as pd
import os
import glob

In [12]:
# Define the directory where individual entropy results are saved
output_entropy_dir = "/Volumes/TwoTeras/1_Experiment_2/Entropy_Results/Window/entropy_results/"
entropy_log_path = "/Volumes/TwoTeras/1_Experiment_2/Entropy_Results/entropy_log_Window_reduced.csv"

# Get list of all entropy result CSV files
entropy_files = glob.glob(os.path.join(output_entropy_dir, "*.csv"))

# Initialize a list to collect DataFrames
dfs = []

# Loop through each file and append its DataFrame with additional columns
for file in entropy_files:
    try:
        # Extract Participant_ID and Session from the file name (assuming format participantID_Session.csv)
        filename = os.path.basename(file)
        participant_id, session = filename.split("_")[0], filename.split("_")[1].split(".")[0]
        
        # Read the file
        df = pd.read_csv(file)

        # Add Participant_ID and Session columns
        df['Participant_ID'] = participant_id
        df['Session'] = session

        # Append to the list of DataFrames
        dfs.append(df)
    except Exception as e:
        print(f"Error reading file {file}: {e}")

# Concatenate all DataFrames into one
if dfs:
    general_entropy_df = pd.concat(dfs, ignore_index=True)

    # Create the new column Agent_ID
    general_entropy_df['Agent_ID'] = general_entropy_df['Collider_Name'].str[:2]
    
    # Create the new column Agent_Type
    general_entropy_df['Agent_Type'] = general_entropy_df['Agent_ID'].astype(int).apply(lambda x: 'Active' if x < 28 else 'Passive')
    
    general_entropy_df['Experiment'] = 2

    # Save the concatenated DataFrame
    general_entropy_df.to_csv(entropy_log_path, index=False)
    print(f"General entropy log saved to {entropy_log_path}")
else:
    print("No entropy result files found or unable to concatenate.")

General entropy log saved to /Volumes/TwoTeras/1_Experiment_2/Entropy_Results/entropy_log_Window_reduced.csv

In [11]:
general_entropy_df.head()

,Trial_ID,Collider_Name,Occurrence_Order,Overall_Transition_Entropy,Participant_ID,Session,Agent_ID,Agent_Type
0,01_Cma_Trial_22,01_Cma,22,0.494550,1031,1,01,Active
1,03_Cma_Trial_16,03_Cma,16,0.340640,1031,1,03,Active
2,09_Cma_Trial_14,09_Cma,14,0.250472,1031,1,09,Active
3,09_Cma_Trial_24,09_Cma,24,0.334480,1031,1,09,Active
4,09_Cma_Trial_26,09_Cma,26,0.314868,1031,1,09,Active

In [4]:
# Create the new column Agent_ID
general_entropy_df['Agent_ID'] = general_entropy_df['Collider_Name'].str[:2]

In [5]:
general_entropy_df.head()

,Trial_ID,Collider_Name,Occurrence_Order,Overall_Transition_Entropy,Agent_ID
0,01_Cma_Trial_22,01_Cma,22,0.494550,01
1,03_Cma_Trial_16,03_Cma,16,0.340640,03
2,09_Cma_Trial_14,09_Cma,14,0.250472,09
3,09_Cma_Trial_24,09_Cma,24,0.334480,09
4,09_Cma_Trial_26,09_Cma,26,0.314868,09